name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build with Makefile
        run: |
          make
          ./main
      - name: Automake and create tarball
        run: |
         autoreconf --install
         ./configure
         make dist
      - name: Build Debian package
        run: |
         dpkg-buildpackage -us -uc

